name: CD

variables:
- name: PACKAGE_USER
  value: jellespijker
- name: PACKAGE_CHANNEL
  value: testing

trigger:
  branches:
    include:
      - main
      - master
      - releases/*
      - refs/tags/v*

pr:
  - main
  - releases/*

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-2022'
    steps:
      - powershell: |
          pip install conan
          conan config install https://github.com/ultimaker/conan-config.git
          conan profile new default --detect
          conan user -p $env:MAPPED_CONAN_PASS -r ultimaker $env:MAPPED_CONAN_USER
        displayName: Prepare Conan environment
        env:
          MAPPED_CONAN_USER: $(CONAN_USER)
          MAPPED_CONAN_PASS: $(CONAN_PASS)
      - powershell: conan create . $(PACKAGE_USER)/$(PACKAGE_CHANNEL) -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing
        displayName: Create Conan package
      - powershell: conan upload "*" -r ultimaker --all -c
        displayName: Upload Conan package(s)
  - job: macOS
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - bash: |
          pip3 install conan
          conan config install https://github.com/ultimaker/conan-config.git
          conan profile new default --detect
          conan user -p $MAPPED_CONAN_PASS -r ultimaker $MAPPED_CONAN_USER
        displayName: Prepare Conan environment
        env:
          MAPPED_CONAN_USER: $(CONAN_USER)
          MAPPED_CONAN_PASS: $(CONAN_PASS)
      - bash: conan create . $(PACKAGE_USER)/$(PACKAGE_CHANNEL) -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing
        displayName: Create Conan package
      - bash: conan upload "*" -r ultimaker --all -c
        displayName: Upload Conan package(s)
  - job: Linux
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - bash: |
          pip install conan
          conan config install https://github.com/ultimaker/conan-config.git
          conan profile new default --detect
          conan user -p $MAPPED_CONAN_PASS -r ultimaker $MAPPED_CONAN_USER
        displayName: Prepare Conan environment
        env:
          MAPPED_CONAN_USER: $(CONAN_USER)
          MAPPED_CONAN_PASS: $(CONAN_PASS)
      - bash: conan create . $(PACKAGE_USER)/$(PACKAGE_CHANNEL) -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing
        displayName: Create Conan package
      - bash: conan upload "*" -r ultimaker --all -c
        displayName: Upload Conan package(s)
