// Copyright (c) 2023. Jelle Spijker
// NailCLipper is released under the terms of the AGPLv3 or higher

#ifndef NAILCLIPPER_INCLUDE_NAILCLIPPER_CONTAINERS_PATHS_HPP
#define NAILCLIPPER_INCLUDE_NAILCLIPPER_CONTAINERS_PATHS_HPP

#endif // NAILCLIPPER_INCLUDE_NAILCLIPPER_CONTAINERS_PATHS_HPP
